// <auto-generated />
using System;
using CourseList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourseList_Demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210421124318_1")]
    partial class _1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourseList.Models.CourseLists", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeegreeId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("DeegreeId");

                    b.ToTable("CourseLists");
                });

            modelBuilder.Entity("CourseList_Demo.Models.DeegreeList", b =>
                {
                    b.Property<int>("DeegreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeegreeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeegreeId");

                    b.ToTable("DeegreeLists");
                });

            modelBuilder.Entity("CourseList.Models.CourseLists", b =>
                {
                    b.HasOne("CourseList_Demo.Models.DeegreeList", "DeegreeList")
                        .WithMany("CourseLists")
                        .HasForeignKey("DeegreeId");

                    b.Navigation("DeegreeList");
                });

            modelBuilder.Entity("CourseList_Demo.Models.DeegreeList", b =>
                {
                    b.Navigation("CourseLists");
                });
#pragma warning restore 612, 618
        }
    }
}
